- name: Upload SSH key to Digital Ocean
  digital_ocean_sshkey: >
      state=present
      name={{ do_email }}
      ssh_pub_key="{{ my_pub_key }}"
      client_id="{{ client_id }}"
      api_key="{{ api_key }}"
  register: do_droplet

- name: Create Digital Ocean droplet 1GB/Ubuntu 14.04 x64/Amsterdam 2
  digital_ocean: >   
    state=present
    command=droplet
    unique_name=true
    name="{{ do_hostname }}"
    client_id="{{ client_id }}"
    api_key="{{ api_key }}"
    size_id={{ size }}
    ssh_key_ids="{{ do_droplet.ssh_key.id }}"
    region_id={{ region }}
    image_id={{ image }}
    wait_timeout=600
  register: do_droplet

- name: ID
  debug: msg="ID is {{ do_droplet.droplet.id }}"
- name: IP
  debug: msg="IP is {{ do_droplet.droplet.ip_address }}"
    
- name: Add new droplet to inventory
  add_host: >
    name="{{ do_droplet.droplet.ip_address }}"
    groups=digital_ocean